### ISSUE TITLE
Integration down ?

### ISSUE THREAD

**Issue by 0r1g1ne** [dmitry-pervushin/toutsurmoneau#2]
Hi,
For several days now, the integration has not been working, and the sensors remain in "unknown" or "unavailable" status.
I can't get any more data, nor do I get any error messages (even when activating the traces).
Attempting to uninstall/reinstall doesn't change anything.
Is the integration still working? If so, this confirms that it's coming from me.
Thanks in advance.

**Comment by dmitry-pervushin** [comment]
Yes, it does…
Would you mind to run “python3 pysuez1.p -u your-user-name -p your-password  -c your-counter-id -vvv” and share the result?

From: 0r1g1ne ***@***.***>
Date: Thursday, 29 February 2024 at 17:49
To: dmitry-pervushin/toutsurmoneau ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dmitry-pervushin/toutsurmoneau] Integration down ? (Issue #2)

Hi,
For several days now, the integration has not been working, and the sensors remain in "unknown" or "unavailable" status.
I can't get any more data, nor do I get any error messages (even when activating the traces).
Attempting to uninstall/reinstall doesn't change anything.
Is the integration still working? If so, this confirms that it's coming from me.
Thanks in advance.

**Comment by 0r1g1ne** [comment]
Line 29 in pysuez1.py
Import pytz
ModuleNotFoundError : no module named 'pytz'

**Comment by dmitry-pervushin** [comment]
--- a/custom_components/toutsurmoneau/manifest.json
+++ b/custom_components/toutsurmoneau/manifest.json
@@ -6,6 +6,6 @@
   "domain": "toutsurmoneau",
   "iot_class": "cloud_polling",
   "name": "ToutSurMonEau.Fr",
-  "requirements": ["aiohttp"],
+  "requirements": ["aiohttp", "pytz"],
   "version": "0.1.2"
}

Would that fix the problem?

If you’re running this on host other that HA, please install it the dependencies – “pip3 install pytz aiohttp”

From: 0r1g1ne ***@***.***>
Date: Thursday, 29 February 2024 at 18:45
To: dmitry-pervushin/toutsurmoneau ***@***.***>
Cc: dmitry-pervushin ***@***.***>, Comment ***@***.***>
Subject: Re: [dmitry-pervushin/toutsurmoneau] Integration down ? (Issue #2)

Line 29 in pysuez1.py
Import pytz
ModuleNotFoundError : no module named 'pytz'

**Comment by 0r1g1ne** [comment]
Yes, it's work,
Great thanks

**Comment by 0r1g1ne** [comment]
Closed
